### ISSUE TITLE
820_kantonal_geschuetztes_Kulturobjekt  verschieben zu nicht zwingend ein Dokument

### ISSUE THREAD

**Issue by Luescher** [edigonzales/ilivalidator-web-service-nplso#1]
Zeile 613 	"Typ_Kt == #N820_kantonal_geschuetztes_Kulturobjekt" verschieben zu nicht zwingend ein Dokument0

Kommt ja vom Kanton in Zukunft.
Und  N821_kommunal_geschuetztes_Kulturobjekt  fehlt bei "CONSTRAINTS OF Typ_Ueberlagernd_Punkt = "  muss auch kein Dokument haben.

**Comment by edigonzales** [comment]
Bin verunsichert: Die sind im `OR`, d.h. die dürfen keine Dokumente haben. Alle Typen die im `AND` sind die Typen, die ein Dokument benötigen. Ich muss leider auch die aufzählen, für die das nicht gilt, sonst funktioniert der Constraint nicht.

**Comment by Luescher** [comment]
N820 ist eben bei "Punkt" im "AND" sollte aber im OR stehen Zeile 613

**Comment by edigonzales** [comment]
fixed https://github.com/edigonzales/ilivalidator-web-service-nplso/commit/a7308d1055b1d3d0efb138ea10a08c3b47728fc9
